### ISSUE TITLE
关于介绍项目的一些建议

### ISSUE THREAD

**Issue by daimiaopeng** [chenshuaihao/NetServer#2]
我觉得应该放几张网站的截图，然后有服务器的话可以搭建Demo，这样的话更加有吸引力。

**Comment by xunshuidezhu** [comment]
> 我觉得应该放几张网站的截图，然后有服务器的话可以搭建Demo，这样的话更加有吸引力。

重点是服务器的开发而不是页面demo的展示，不需要放什么网站
